default:
  artifacts:
    expire_in: 1 day

stages:
  - prepare
  - lint
  - build

variables:
  ucs: 444
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: none
  GIT_DEPTH: "3"
  DEB: docker-registry.knut.univention.de/phahn/ucs-devbase:$ucs
  DOC: docker-registry.knut.univention.de/docbook
  LINT: docker-registry.knut.univention.de/ucslint:$ucs
  APTLY: http://omar.knut.univention.de:11620/api
  APT: http://omar.knut.univention.de/build2/git

prepare aptly:
  stage: prepare
  image: curlimages/curl
  script:
    - "$CI_PROJECT_DIR/.gitlab-ci/aptly-create || :"
    - $CI_PROJECT_DIR/.gitlab-ci/aptly-publish
  environment:
    name: $CI_COMMIT_REF_NAME
    url: $APT/dists/$CI_COMMIT_REF_SLUG/
    on_stop: drop aptly
    auto_stop_in: 6 month

drop aptly:
  stage: prepare
  variables:
    GIT_STRATEGY: none
  image: curlimages/curl
  script:
    - "curl --silent --show-error -X DELETE $APTLY/publish//$CI_COMMIT_REF_SLUG || :"
    - "curl --silent --show-error -X DELETE $APTLY/repos/$CI_COMMIT_REF_SLUG || :"
  when: manual
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop

.lint:
  stage: lint
  image: $LINT
  script:
    - ucslint $base

.deb:
  stage: build
  image: $DEB
  before_script:
    - echo "deb [trusted=yes] $APT $CI_COMMIT_REF_SLUG main" >"/etc/apt/sources.list.d/$CI_COMMIT_REF_SLUG.list"
    - apt-get -qq update
    - cd $base
    - apt-get -qq build-dep .
  script:
    - dpkg-buildpackage -uc -us -b --jobs-try=auto
  after_script:
    - apt-get -qq --no-install-recommends install curl
    - .gitlab-ci/aptly-upload ${base}_*.changes

.doc:
  stage: build
  image: $DOC
  script:
    - make -C $base install DESTDIR=$CI_PROJECT_DIR/public
  artifacts:
    paths:
      - public

prepare ucslint:
  stage: prepare
  services:
    - name: docker-registry.knut.univention.de/ucs/docker:dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  tags:
    - docker
  image: docker:stable
  script:
    - docker build --pull -t $LINT -f .gitlab-ci/Dockerfile.ucslint packaging/ucslint
    - docker push $LINT
  rules:
    - changes:
      - packaging/ucslint/**/*
